import Foundation

/// The author of a message in a chatbot conversation.
public enum ChatRole: String, Codable, CaseIterable, Sendable {
    /// A message entered by the person using the host application.
    case user

    /// A message generated by the configured model.
    case assistant
}

/// The delivery state of a message.
public enum ChatMessageStatus: String, Codable, Sendable {
    /// The message has been accepted but processing has not finished.
    case pending

    /// The assistant is currently streaming this message.
    case streaming

    /// The message completed successfully.
    case complete

    /// The message could not be completed.
    case failed

    /// Generation was cancelled by the person or host application.
    case cancelled
}

/// A source supplied to the model as application context.
///
/// Source cards communicate which material was provided to a model. They aren't
/// sentence-level citations and don't guarantee that every generated statement is
/// supported by the source.
public struct ChatSource: Identifiable, Codable, Equatable, Sendable {
    /// A stable identifier supplied by the host application.
    public let id: String

    /// A short, human-readable source name.
    public let title: String

    /// An optional location that the interface can open for more information.
    public let url: URL?

    /// Optional domain-neutral values for custom source-card styles.
    public let metadata: [String: String]

    /// Creates a source displayed alongside a generated response.
    ///
    /// - Parameters:
    ///   - id: A stable identifier for deduplication.
    ///   - title: A concise display title.
    ///   - url: An optional destination containing the source material.
    ///   - metadata: Additional values interpreted by a custom ``ChatbotStyle``.
    public init(
        id: String,
        title: String,
        url: URL? = nil,
        metadata: [String: String] = [:]
    ) {
        self.id = id
        self.title = title
        self.url = url
        self.metadata = metadata
    }
}

/// A single user or assistant message.
public struct ChatMessage: Identifiable, Codable, Equatable, Sendable {
    /// The stable message identifier.
    public let id: UUID

    /// The message author.
    public let role: ChatRole

    /// The current textual content.
    public var content: String

    /// The time at which the message was created.
    public let createdAt: Date

    /// The message's current delivery state.
    public var status: ChatMessageStatus

    /// Sources supplied while producing an assistant response.
    public var sources: [ChatSource]

    /// A normalized failure associated with this message, when present.
    public var failure: ChatbotError?

    /// Creates a conversation message.
    ///
    /// - Parameters:
    ///   - id: The message identifier. Preserve it when persisting history.
    ///   - role: The message author.
    ///   - content: The message text.
    ///   - createdAt: The creation time.
    ///   - status: The delivery state.
    ///   - sources: Context sources associated with an assistant answer.
    ///   - failure: A normalized failure when generation didn't complete.
    public init(
        id: UUID = UUID(),
        role: ChatRole,
        content: String,
        createdAt: Date = Date(),
        status: ChatMessageStatus = .complete,
        sources: [ChatSource] = [],
        failure: ChatbotError? = nil
    ) {
        self.id = id
        self.role = role
        self.content = content
        self.createdAt = createdAt
        self.status = status
        self.sources = sources
        self.failure = failure
    }
}

/// A persistable conversation and its ordered messages.
public struct ChatConversation: Identifiable, Codable, Equatable, Sendable {
    /// The identifier used by an optional ``ChatHistoryStore``.
    public let id: String

    /// Messages in display order.
    public var messages: [ChatMessage]

    /// The last time the conversation changed.
    public var updatedAt: Date

    /// Creates a conversation.
    ///
    /// - Parameters:
    ///   - id: A stable identifier, commonly tied to a user or app feature.
    ///   - messages: Previously persisted messages in display order.
    ///   - updatedAt: The last modification time.
    public init(
        id: String = UUID().uuidString,
        messages: [ChatMessage] = [],
        updatedAt: Date = Date()
    ) {
        self.id = id
        self.messages = messages
        self.updatedAt = updatedAt
    }
}

/// A piece of application-owned information retrieved for a prompt.
public struct ChatKnowledgeItem: Identifiable, Codable, Equatable, Sendable {
    /// A stable identifier for the knowledge item.
    public let id: String

    /// A concise title suitable for a source card.
    public let title: String

    /// The trusted context supplied to the model.
    public let content: String

    /// An optional location where the person can inspect the source.
    public let url: URL?

    /// Optional values used by custom source-card styles.
    public let metadata: [String: String]

    /// Creates an application knowledge item.
    ///
    /// - Parameters:
    ///   - id: A stable identifier.
    ///   - title: A human-readable title.
    ///   - content: The context supplied to the model.
    ///   - url: An optional source destination.
    ///   - metadata: Additional domain-specific display values.
    public init(
        id: String,
        title: String,
        content: String,
        url: URL? = nil,
        metadata: [String: String] = [:]
    ) {
        self.id = id
        self.title = title
        self.content = content
        self.url = url
        self.metadata = metadata
    }

    /// A display source derived from this knowledge item.
    public var source: ChatSource {
        ChatSource(id: id, title: title, url: url, metadata: metadata)
    }
}
